### ISSUE TITLE
Possible to add vicuna-33b support ?

### ISSUE THREAD

**Issue by gvigroux** [thekevinscott/vicuna-7b#2]
Would be great :)
IT's much more efficient.

**Comment by thekevinscott** [comment]
This project is a wrapper around [`web-llm`](https://github.com/mlc-ai/web-llm), specifically to enable easy consumption of the LLM without having to scaffold the whole UI like `web-llm` had set up originally.

[It appears that the `web-llm` have set up their own `npm` package that offers largely the same functionality](https://www.npmjs.com/package/@mlc-ai/web-llm), along with easy access to all the latest models.

Is there a reason you're looking to leverage this package instead of theirs? If so, I'd love to know. My instinct would be to deprecate this package in favor of theirs, unless there is a compelling reason to keep this one active.

**Comment by gvigroux** [comment]
Thank s for the explanation.I agree with you.
